import win32com.client
import subprocess
import time
import os
import pandas as pd
from datetime import datetime

# =================================================================
# --- CONFIGURATION (DE-IDENTIFIED) ---
# =================================================================
# [DE-IDENTIFIED] Use generic placeholders for corporate paths
FILE_PATH = r"O:\Shared drives\YOUR_PROJECT_FOLDER\data\source_data.xlsx"
SAP_SYSTEM_ID = "YOUR_SAP_SYSTEM_ID"
SAP_LOGON_PATH = r"C:\Program Files (x86)\SAP\FrontEnd\SAPgui\saplogon.exe"
MASTER_DATA_DIR = r"O:\Shared drives\YOUR_PROJECT_FOLDER\MasterData"

# =================================================================
# --- DATA PROCESSING HELPERS ---
# =================================================================

def get_sap_dataframe(txt_path):
    """Parses SAP exported TXT files into a clean Pandas DataFrame."""
    try:
        # Wait for file to be generated by SAP
        for _ in range(10):
            if os.path.exists(txt_path) and os.path.getsize(txt_path) > 0:
                break
            time.sleep(1)
        
        df = pd.read_csv(txt_path, sep='\t', skiprows=3, dtype=str, engine='python')
        df = df.dropna(axis=1, how='all')
        df = df.apply(lambda x: x.str.strip() if hasattr(x, "str") else x)
        return df
    except Exception as e:
        print(f"Error parsing SAP export: {e}")
        return pd.DataFrame()

def import_data(file_path):
    """Imports staging data from Excel or CSV."""
    if not os.path.exists(file_path):
        print(f"Error: Source file not found at {file_path}")
        return None
    try:
        if file_path.lower().endswith('.csv'):
            df = pd.read_csv(file_path, header=0)
        else:
            df = pd.read_excel(file_path, header=0, engine='openpyxl')
        return df.fillna('').astype(str)
    except Exception as e:
        print(f"Data Import Error: {e}")
        return None

# =================================================================
# --- SAP GUI INTERFACE ---
# =================================================================

def connect_to_sap():
    """Connects to active SAP session or initializes a new one."""
    try:
        SapGuiAuto = win32com.client.GetObject("SAPGUI")
        application = SapGuiAuto.GetScriptingEngine
        connection = application.OpenConnection(SAP_SYSTEM_ID, True)
        return connection.Children(0)
    except Exception:
        try:
            subprocess.Popen(SAP_LOGON_PATH)
            time.sleep(10)
            SapGuiAuto = win32com.client.GetObject("SAPGUI")
            return SapGuiAuto.GetScriptingEngine.OpenConnection(SAP_SYSTEM_ID, True).Children(0)
        except Exception as e:
            print(f"Critical: SAP Connection Failed: {e}")
            return None

# =================================================================
# --- CORE BUSINESS LOGIC (CV01N / CV02N) ---
# =================================================================

def run_sap_upload():
    data_df = import_data(FILE_PATH)
    session = connect_to_sap()
    if data_df is None or session is None: return

    try:
        print(f"Commencing SAP Batch Processing for {len(data_df)} records...")
        
        # Part A: Update Internal Reference Index (ZSE16 Transaction)
        session = update_document_index(session)
        
        # Part B: Process CV01N - Document Creation
        for index, row in data_df.iterrows():
            mat_no = str(row.iloc[0]).strip()
            if not mat_no: continue

            # Navigation to CV01N
            session.findById("wnd[0]/tbar[0]/okcd").text = "/nCV01N"
            session.findById("wnd[0]").sendVKey(0)
            
            # [DE-IDENTIFIED] Using generic Document Type 'ART'
            session.findById("wnd[0]/usr/ctxtDRAW-DOKAR").text = "ART"
            session.findById("wnd[0]").sendVKey(0)

            # Map Excel data to SAP Fields
            session.findById("wnd[0]/usr/tabsTAB_MAIN/tabpTSMAIN/ssubSCR_MAIN:SAPLCV110:0102/txtDRAT-DKTXT").text = row.iloc[1] # Description
            session.findById("wnd[0]/usr/tabsTAB_MAIN/tabpTSMAIN/ssubSCR_MAIN:SAPLCV110:0102/ctxtTDWST-STABK").text = "PR"
            
            # File Attachment Logic
            session.findById("wnd[0]/usr/tabsTAB_MAIN/tabpTSMAIN/ssubSCR_MAIN:SAPLCV110:0102/btnPB_FILE_CREATE").press()
            session.findById("wnd[1]/usr/ctxtDRAW-DAPPL").text = "PDF"
            session.findById("wnd[1]/usr/ctxtDRAW-FILEP1").text = row.iloc[13] # PDF Path
            session.findById("wnd[1]/tbar[0]/btn[0]").press()

            # Classification & Object Links
            session.findById("wnd[0]/usr/tabsTAB_MAIN/tabpTSLINKS").select()
            session.findById("wnd[0]/usr/tabsTAB_MAIN/tabpTSLINKS/ssubSCR_MAIN:SAPLCV130:0404/tabsSELECT_OBJLINKSTRIP_400/tabpOBJTB01/ssubSUBSCRN_OBJLINK:SAPLCV130:1201/tblSAPLCV130TAB_X/ctxtMARA-MATNR[0,0]").text = mat_no
            
            # Final Save
            session.findById("wnd[0]").sendVKey(11) 
            doc_id = session.findById('/app/con[0]/ses[0]/wnd[0]/usr/ctxtDRAW-DOKNR').text
            print(f"Success: Material {mat_no} linked to Document {doc_id}")

            # [DE-IDENTIFIED] Audit Logging
            log_result_locally(row, doc_id)

        print("Total Processing Complete.")

    except Exception as e:
        print(f"Runtime Exception: {e}")

def update_document_index(session):
    """Extracts the DRAD table to verify existing object links."""
    session.findById("wnd[0]/tbar[0]/okcd").text = "/nSE16"
    session.findById("wnd[0]").sendVKey(0)
    session.findById("wnd[0]/usr/ctxtDATABROWSE-TABLENAME").text = "DRAD"
    session.findById("wnd[0]").sendVKey(0)
    
    # Export logic to local directory for cross-referencing
    output_file = os.path.join(MASTER_DATA_DIR, "document_masterdata.txt")
    # ... (Export UI scripting remains here, but paths are now derived from MASTER_DATA_DIR)
    return session

def log_result_locally(row, doc_id):
    """Appends successful transaction to a local CSV audit trail."""
    csv_path = os.path.join(MASTER_DATA_DIR, 'transaction_log.csv')
    log_df = pd.DataFrame([row])
    log_df['generated_doc_id'] = doc_id
    log_df['timestamp'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_df.to_csv(csv_path, mode='a', header=not os.path.exists(csv_path), index=False, encoding='utf-8-sig')

if __name__ == "__main__":
   run_sap_upload()
